### ISSUE TITLE
Cannot retrieve comment

### ISSUE THREAD

**Issue by MalvinJu** [rarcega/instagram-scraper#119]
There's an error getting comments in item['code'] line 432

**Comment by murdrae** [comment]
I believe this is the error you're seeing:
`Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 746, in main
    scraper.scrape()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 340, in scrape
    self.get_media(dst, executor, future_to_item, user_details)
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 432, in get_media
    item['comments']['data'] = list(self.query_comments_gen(item['code']))
KeyError: 'code'`

**Comment by rarcega** [comment]
Fixed in v1.5.10

To upgrade: pip install instagram-scraper --upgrade
