### ISSUE TITLE
Bug in json decoder

### ISSUE THREAD

**Issue by VasiliPupkin256** [rarcega/instagram-scraper#120]
Traceback (most recent call last):
  File "...\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "...\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\Scripts\instagram-scraper.exe\__main__.py", line 9, in <module>
  File "...\lib\site-packages\instagram_scraper\app.py", line 746, in main
    scraper.scrape()
  File "...\lib\site-packages\instagram_scraper\app.py", line 339, in scrape
    user_details = self.get_user_details(username)
  File "...\lib\site-packages\instagram_scraper\app.py", line 395, in get_user_details
    return json.loads(resp.text)['user']
  File "...\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "...\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "...\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by VasiliPupkin256** [comment]
Can be reproduced on any nonexistent username

**Comment by Nicksxs** [comment]
```
Searching aohsuehfu for posts: 0 media [00:00, ? media/s]Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 746, in main
    scraper.scrape()
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 340, in scrape
    self.get_media(dst, executor, future_to_item, user_details)
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 411, in get_media
    unit=' media', disable=self.quiet):
  File "/usr/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 467, in query_media_gen
    media, end_cursor = self.__query_media(user_details['id'], end_cursor)
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 492, in __query_media
    nodes = self._get_nodes(container)
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 271, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 287, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 305, in __get_media_details
    return json.loads(resp.text)['graphql']['shortcode_media']
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
i face similar problem,but i check the username is exist
username: aohsuehfu
