### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Nicksxs** [rarcega/instagram-scraper#123]
```
Searching aohsuehfu for posts: 0 media [00:00, ? media/s]Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 746, in main
    scraper.scrape()
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 340, in scrape
    self.get_media(dst, executor, future_to_item, user_details)
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 411, in get_media
    unit=' media', disable=self.quiet):
  File "/usr/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 467, in query_media_gen
    media, end_cursor = self.__query_media(user_details['id'], end_cursor)
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 492, in __query_media
    nodes = self._get_nodes(container)
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 271, in _get_nodes
    return [self.augment_node(node['node']) for node in container['edges']]
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 287, in augment_node
    details = self.__get_media_details(node['shortcode'])
  File "/usr/local/lib/python2.7/site-packages/instagram_scraper/app.py", line 305, in __get_media_details
    return json.loads(resp.text)['graphql']['shortcode_media']
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
i check the username is exist
username: aohsuehfu

**Comment by rarcega** [comment]
This is odd. If you visit that user's page, you'll see that one of the posts redirects you to a different post:

`https://www.instagram.com/p/Ba8_e-Eldmp/`

redirects to:

`https://www.instagram.com/p/Ba8_kFYFs4Z/`

which is causing the issue.
