### ISSUE TITLE
User does not exist error

### ISSUE THREAD

**Issue by xporterfield** [rarcega/instagram-scraper#129]
Anyone else getting this error (with users that definitely do exist publically)?

Searching minniedlamini for profile pic: 100% 1/1 [00:00<00:00, 1003.66 images/s]
Searching minniedlamini for posts: 0 media [00:00, ? media/s]ERROR: Failed to get media for minniedlamini
Traceback (most recent call last):
  File "c:\anaconda2\envs\instagram-scraper\lib\site-packages\instagram_scraper\app.py", line 431, in media_gen
    media = self.fetch_media_json(username, max_id=None)
  File "c:\anaconda2\envs\instagram-scraper\lib\site-packages\instagram_scraper\app.py", line 464, in fetch_media_json
    raise ValueError('User {0} does not exist'.format(username))
ValueError: User minniedlamini does not exist

**Comment by rarcega** [comment]
Instagram recently removed an endpoint which warranted some changes. Have you tried with the latest version of the scraper?
`pip install instagram-scraper --upgrade`

**Comment by rarcega** [comment]
Can you double check with `pip show instagram-scraper`? I ask because the error message in your original post was changed--it's displaying an error message from a previous version. I tried the same user with the -m argument with no issues.

```bash
Name: instagram-scraper
Version: 1.5.14
...
```

**Comment by ashvar** [comment]
Completely uninstall it and start again. Something goes wrong with —upgrade.

**Comment by xporterfield** [comment]
I made sure I was using 1.5.14.  The error still occurs.  I then tried a complete uninstall and reinstall, same issue.

> (instagram-scraper) E:\Git\instagram-scraper>instagram-scraper paulapattonofficial
> Searching paulapattonofficial for profile pic: 100% 1/1 [00:00<?, ? images/s]
> Searching paulapattonofficial for posts: 0 media [00:00, ? media/s]ERROR: Failed to get media for paulapattonofficial
> Traceback (most recent call last):
>   File "c:\anaconda2\envs\instagram-scraper\lib\site-packages\instagram_scraper\app.py", line 431, in media_gen
>     media = self.fetch_media_json(username, max_id=None)
>   File "c:\anaconda2\envs\instagram-scraper\lib\site-packages\instagram_scraper\app.py", line 464, in fetch_media_json
>     raise ValueError('User {0} does not exist'.format(username))
> ValueError: User paulapattonofficial does not exist
> 
> Downloading: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.61it/s]
>

**Comment by clublek** [comment]
I'm having the same issue, for lots of users in my users.txt. Upgraded to the latest version as well.
ERROR: Error getting user details for .... Please verify that the user exists.
