### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by bschollnick** [rarcega/instagram-scraper#139]
I just got a Http Status 429 with Instagram-scraper (Too Many requests).  

My first thought would simply be to add a time.sleep(xx) into the code, triggered by a command line option...  Is there a different more preferred way you would rather have implemented?

Any suggestions before I start looking to implement something?

**Comment by VasiliPupkin256** [comment]
Does it appear as ERROR or WARNING in instagram-scraper.log? 
Server response with this code sometimes but usually it passes after repeat.
I have limited the number of concurrent requests to 5, it was set to 10 before that and this error was silently ignored by scraper. The mechanism of delays and repeats can be tweaked further if this response becomes common.

**Comment by bschollnick** [comment]
As a warning, but it does kill the current session fetching from instagram, and exits the application.
So it's listed as a warning, but is treated as a fatal error.

2017-12-21 03:12:49,077 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=259559440&first=100&after=
2017-12-21 03:12:54,149 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=259559440&first=100&after=
2017-12-21 03:13:04,234 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=259559440&first=100&after=
2017-12-21 03:13:24,329 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=259559440&first=100&after=
2017-12-21 03:14:04,534 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=259559440&first=100&after=
2017-12-21 03:15:42,078 - instagram_scraper.app - ERROR - User mangosirene is private
2017-12-21 03:15:49,319 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=182502664&first=100&after=
2017-12-21 03:15:54,383 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=182502664&first=100&after=
2017-12-21 03:16:17,048 - instagram_scraper.app - ERROR - Unable to scrape user - mckaylamaroney
2017-12-21 03:16:45,894 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=11771979&first=100&after=
2017-12-21 03:16:50,961 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=11771979&first=100&after=
2017-12-21 03:17:31,919 - instagram_scraper.app - ERROR - Unable to scrape user - morningdew96
2017-12-21 03:18:31,284 - instagram_scraper.app - ERROR - Unable to scrape user - rafaela_gonzalez_cosplay
2017-12-21 03:18:51,247 - instagram_scraper.app - ERROR - Unable to scrape user - realdelaniefrances
2017-12-21 03:19:26,445 - instagram_scraper.app - ERROR - User safira_scarlet is private
2017-12-21 03:20:18,862 - instagram_scraper.app - ERROR - Unable to scrape user - spacepizzacosplay
2017-12-21 03:20:19,126 - instagram_scraper.app - ERROR - User sparky.cosplay is private
2017-12-21 03:21:59,232 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-21 03:22:04,296 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-21 03:22:14,394 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-21 03:22:34,508 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-21 03:23:14,723 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=

**Comment by bschollnick** [comment]
I found the actual execution error...

Searching ver1sa for posts: 0 media [00:00, ? media/s]
Searching verabambilive for posts: 0 media [00:00, ? media/s]Traceback (most recent call last):
  File "/Users/Benjamin/library/Python/2.7/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 895, in main
    scraper.scrape()
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 427, in scrape
    self.get_media(dst, executor, future_to_item, user)
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 504, in get_media
    unit=' media', disable=self.quiet):
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 566, in query_media_gen
    media, end_cursor = self.__query_media(user['id'], end_cursor)
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 584, in __query_media
    resp = self.safe_get(QUERY_MEDIA.format(id, end_cursor))
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 95, in safe_get
    raise StatusCodeException('Bad status code: {0}'.format(response.status_code))
instagram_scraper.app.StatusCodeException: Bad status code: 429

**Comment by VasiliPupkin256** [comment]
Previously it repeated indefinitely on error in this function:
```
def __query_media(self, id, end_cursor=''):
    resp = self.session.get(...)
    if resp.status_code == 200:
        ...
    else:
        ...
        return self.__query_media(id, end_cursor)
```
now exits after a minute of unsuccessful retries. 

You may lower the number of `MAX_CONCURRENT_DOWNLOADS` or set the number of retries `MAX_RETRIES` to infinity to overcome this issue or make command line switches for this two. 

It is also interesting to try media downloads in separate anonymous sessions. Instagram doesn't require authorization to download media files through direct links and I don't think that instagram is blocking IPs otherwise users under NAT have faced huge problems. Try change the code in `download` function, instead of `self.session.get` use a new local session or `requests.get` function directly. I can't reproduce error on my internet connection and can't test this trick.

**Comment by bschollnick** [comment]
Changing MAX_CONCURRENT_DOWNLOADS, to 2 had no effect.  Same issue.

In my situation, I am using -f with a file of 190 entries for the first run (A to L), and another file of 121 entries for the second run (M to Z).

I'll take a look at modifying download media files.  Or maybe, we detect the 429 and then switch sessions instead...?

**Comment by VasiliPupkin256** [comment]
I also use it with -f switch the huge list. But also passing -u and -p of a temporal account authorized on some private accounts from the list. I am also thinking to implement a feature of automate authorization requests for private accounts. 429 error happens to me rarely and disappear after one or two retries. The connection termination errors are much more common. You can increase `MAX_RETRIES` and it will work as before, but I don't know how to speed it up in this case and how to trick instagram from banning your IP or session. Is it only a session i.e. cookie thing or is it an IP based policy. Will liming the number of requests per second helps or is it an unavoidable consequence of mass download and it will only slows things down compared to wait and retry algorithm.

**Comment by bschollnick** [comment]
Well, I changed MAX_CONCURRENT_DOWNLOADS to 1, and added:

                print "\nPausing In-between users for 30 seconds."
                for x in range(0, 2):
                    print ".",
                    time.sleep(10)

In scrape, around line 445...

The console output is obviously being cached...  But other than that, it worked, but significantly slower due to the sleep's...

No 429's encountered, but this was much more brute force then I would like.

Of course, the final product will be command line triggered, but I'm considering reworking it to have a 2 second delay if nothing is found to download, and if any download's occurred adding a ~10 second delay.  But I need to wait a few days, and try again, and see if it triggers any 429 errors with a shorter delay.

**Comment by VasiliPupkin256** [comment]
Do you use `--latest` switch? With this switch it is probably calling `__query_media` once for every user and the delay you added becomes the delay between calls to `__query_media`. But the function is called many times for the same user if there were no media downloaded for the user or if there was no switch. If this is the case then the delay should be somehow added there between calls to that function. Try to run it without the switch and see if 429 errors reappear.

Also, as I understand it worked for you before and stopped working after my commit that introduced a `MAX_RETRIES` limit. Right? Why increasing the `MAX_RETRIES` didn't work then?

**Comment by bschollnick** [comment]
I do use --latest....  

I haven't tried increasing max_retries, because it doesn't make sense that would change anything...  This appears to be a hard limit on throttling from instagram, and even when it aborts, and then the next session (M-Z) starts up, it dies with a 429 error.  The only way I see that solving it would be to set it to a extremely high max_retries value.

But running without --latest is significantly slower...

**Comment by VasiliPupkin256** [comment]
But it did infinite retries in past and works for you. The function `__query_media` that die now have always do this, it waited a few seconds and called itself on error indefinitely. I have just made this retry mechanism more arranged, put it everywhere and limits the number of retries.

I don't suggest you to remove `--latest` in your usecase, just try it without this switch before commiting your fix. If you always run it with `--latest` and the limit is on the number of calls to `__query_media` then the delay should be put there not between users. The function `__query_media` may be called dozens of times during the one user scrape if there were no `--latest` switch or no data downloaded before.

**Comment by bschollnick** [comment]
Without the --latest flag, actually got a 429 error after 6 accounts being scraped.
That's with  MAX_CONCURRENT_DOWNLOADS set to 5 (default).  

Reducing MAX_CONCURRENT_DOWNLOADS to 1, didn't even get pass one account, before 429-ing... Although, the M-Z run right afterwards, ended up  going through 13 accounts...

I'll try boosting the max_retries to 50, and see if that makes a difference, as per your last note.

**Comment by VasiliPupkin256** [comment]
> Without the --latest flag, actually got a 429 error after 6 accounts being scraped

With this "Pausing In-between users for 30 seconds"? If the delay between users doesn't help then the delay should be put there in the function `__query_media` or even in the `safe_get` function itself effectively limiting the number of json requests per minute. But this would be very slow...

> I'll try boosting the max_retries to 50

Ok try it and measure its working time if it pass. Also look into `instagram-scraper.log` where it logs all the retries.

**Comment by bschollnick** [comment]
Just be clear, I removed the sleeps from the code, for the testing above.

Running effectively stock code (--latest flag used), with retries set to 50, did successfully run without errors.

And there was a minimal number of 429 errors...

2017-12-25 20:48:28,457 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=27055209&first=100&after=
2017-12-25 20:48:33,552 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=27055209&first=100&after=
2017-12-25 20:48:43,645 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=27055209&first=100&after=
2017-12-25 20:49:03,754 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=27055209&first=100&after=
2017-12-25 20:49:43,973 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=27055209&first=100&after=
2017-12-25 20:51:04,246 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=27055209&first=100&after=
2017-12-25 20:56:53,691 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=1194579752&first=100&after=AQC7GNi-3Cd-u4MaGu12AUg7OQSlRkMy9q-AcVoDSHqJ_AwSVpHIg41M2B4AoJjo1XDq7p7u-MweLD5-3FjqsITfgA9PajUMrvY6ZePpr4IJ8w
2017-12-25 20:56:58,755 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=1194579752&first=100&after=AQC7GNi-3Cd-u4MaGu12AUg7OQSlRkMy9q-AcVoDSHqJ_AwSVpHIg41M2B4AoJjo1XDq7p7u-MweLD5-3FjqsITfgA9PajUMrvY6ZePpr4IJ8w
2017-12-25 20:59:34,367 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-25 20:59:39,432 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-25 20:59:49,559 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-25 21:00:09,684 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-25 21:00:49,863 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=
2017-12-25 21:02:10,134 - instagram_scraper.app - WARNING - Retry after exception StatusCodeException('Bad status code: 429',) on https://www.instagram.com/graphql/query/?query_id=17888483320059182&id=13832398&first=100&after=

So I guess, my recommendation would be to change the MAX_RETRIES value to 10 or maybe 15 for default...

**Comment by VasiliPupkin256** [comment]
It slows down exponentially. First it wait 5 sec then 10 sec then 20 sec etc. 15 retries on the same requested url is a month of waiting already. The question is either stop the scrape process or do it indefinitely until Ctrl+C is pressed.

**Comment by bschollnick** [comment]
Oh, I didn’t realize that it was an exponential delay.  Then 10 should be fine…  Did I miss this in the documentation?

	- Benjamin

**Comment by VasiliPupkin256** [comment]
It is not documented. I've chosen these constants to get one and a half minutes of cumulative waiting time. 10 retries would be 42 min. I think it would already be considered as a hang by the user. I'd suggest to make a command line switch that set retries to indefinite value i.e. sys.maxsize. Call it `--keep-trying` or similar.

**Comment by muthu-kc** [comment]
I found a simple way to avoid rate limits. We are missing something to send something because of that we are getting rate limited. Before that, within 10 requests I will get rate limited. but now I can able to get 100K likes without any problem.

**Comment by VasiliPupkin256** [comment]
@muthu-kc please share the solution code

**Comment by arpitshah99-cpu** [comment]
@muthu-kc , can you share the workaround/solution you used?
Thanks in Advance.
