### ISSUE TITLE
Read data time out

### ISSUE THREAD

**Issue by jervislam0911** [rarcega/instagram-scraper#152]
Hi @rarcega,

I run the command instagram-scraper lol --tag --media-metadata --maximum 9 and it takes very long to scrapy the data. and it hit the HTTPPoll error. (Read data timeout)

Any ideas why would cause that issue?

Thanks

**Comment by gvkalra** [comment]
For me, it happened because of slow internet connection.

Try raising timeout values in [this](https://github.com/rarcega/instagram-scraper/blob/master/instagram_scraper/constants.py#L22) file:

```python
MAX_CONCURRENT_DOWNLOADS = 5
CONNECT_TIMEOUT = 100
MAX_RETRIES = 5
RETRY_TIMEOUT = 100
```

**Comment by VasiliPupkin256** [comment]
If the issue caused by CONNECT_TIMEOUT please report what value solved the issue for you

**Comment by gvkalra** [comment]
100 worked for me...

**Comment by VasiliPupkin256** [comment]
@gvkalra it is one and a half minute. What is your connection speed that you need such a long delay to just establish a connection?

**Comment by gvkalra** [comment]
@VasiliPupkin256 well, sorry I didn't mention my laziness to fine-tune the value. 5sec. wasn't working out for me and the internet was really in a bad shape at that time. So I simply set it to 100sec and left for the day. Next day, my dataset was ready without any errors!

**Comment by VasiliPupkin256** [comment]
Setting CONNECT_TIMEOUT to a huge value will result in unresponsive scraper behaviour. As far as I know connection process can't be aborted from inside python. If it stuck for some reason and the user press Ctrl+C he will need to wait the whole CONNECTION_TIMEOUT interval in worst case before program terminates. If connection timeout is really needed to be that long to get the job done then we should change it though.

**Comment by megonzalezocampo** [comment]
Hi, i have the same problem: 

C:\Users\megon\Desktop\tesis>instagram-scraper baires --tag -m 25
Searching baires for posts: 0 media [00:00, ? media/s]Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\instagram-scraper.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 889, in main
    scraper.scrape_hashtag()
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 247, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 268, in __scrape_query
    disable=self.quiet):
  File "c:\python27\lib\site-packages\tqdm\_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 311, in __query_gen
    nodes, end_cursor = self.__query(url, entity_name, query, end_cursor)
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 327, in __query
    resp = self.safe_get(url.format(query, end_cursor))
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 93, in safe_get
    response = self.session.get(timeout=CONNECT_TIMEOUT, *args, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.instagram.com', port=443): Read timed out. (read timeout=5)
 
If it's not too much trouble, please can you tell me what should I do to raising timeout values?

ps: yes i don´t write one single line of code and my english is very poor too!
