### ISSUE TITLE
Not able to scrape on hashtag

### ISSUE THREAD

**Issue by hahamark1** [rarcega/instagram-scraper#153]
The scraper does not return any results when the --tag tag is added.

instagram-scraper 'car' --tag
Searching car for posts: 0 media [00:00, ? media/s]

**Comment by taesung89** [comment]
Did you wait long enough? 
I seem to have to same issue but 

`instagram-scraper nofilter --tag -m 10`

worked.

**Comment by gvkalra** [comment]
@hahamark1 try this:
```
instagram-scraper car --tag
```
Notice no quotes around the tag "car"

**Comment by Meikesch** [comment]
I have the same issue, I can scrape up to a maximum of 10 images, but when I set a limit above that, or I don't set a limit at all, it gives an error. It did work a few weeks ago. Does anyone know how to solve this?

instagram-scraper snapchatfilter --tag --media-types image --latest
Searching snapchatfilter for posts: 356 media [02:58,  1.99 media/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.instagram.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.18', 'console_scripts', 'instagram-scraper')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 889, in main
    scraper.scrape_hashtag()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 247, in scrape_hashtag
    self.__scrape_query(self.query_hashtag_gen)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 268, in __scrape_query
    disable=self.quiet):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tqdm/_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 320, in __query_gen
    nodes, end_cursor = self.__query(url, entity_name, query, end_cursor)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 327, in __query
    resp = self.safe_get(url.format(query, end_cursor))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 93, in safe_get
    response = self.session.get(timeout=CONNECT_TIMEOUT, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.instagram.com', port=443): Read timed out. (read timeout=5)
