### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by aringhosh** [rarcega/instagram-scraper#199]
`instagram-scraper <some_user> -m 10 -t image --media-metadata` gives me this 

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/bin/instagram-scraper", line 11, in <module>
>     sys.exit(main())
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 1077, in main
>     scraper.scrape()
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 558, in scrape
>     user = self.get_user(username)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/instagram_scraper/app.py", line 630, in get_user
>     user = json.loads(resp)['user']
> KeyError: 'user'

What's wrong?

**Comment by aringhosh** [comment]
Alright, I updated the package, its all working now!
