### ISSUE TITLE
Login failing issue

### ISSUE THREAD

**Issue by Develop-CharlieLee** [rarcega/instagram-scraper#225]
I checked that instagram-scraper ver 1.5.32. worked very well on 4.29. 06:00 UTC, but starts to fail logging in when I checked on 4.29. 18:00 UTC. Login method might be changed.

**Comment by dmoreno1994** [comment]
Instagram changed method to authenticate.. Try this in login function:

    self.session.get(BASE_URL)
    self.session.headers.update({'X-CSRFToken': self.session.cookies.get_dict()['csrftoken']})

**Comment by rbnali** [comment]
@dmoreno1994 I still get the following error when modifying the _app.py_ script

```
Traceback (most recent call last):
  File "/Users/robin/anaconda3/envs/analytics/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/Users/robin/anaconda3/envs/analytics/lib/python3.6/site-packages/instagram_scraper/app.py", line 1136, in main
    scraper.login()
  File "/Users/robin/anaconda3/envs/analytics/lib/python3.6/site-packages/instagram_scraper/app.py", line 215, in login
    self.session.headers.update({'X-CSRFToken': self.session.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'
```
