### ISSUE TITLE
Login Error - Stories

### ISSUE THREAD

**Issue by clublek** [rarcega/instagram-scraper#233]
Can't download stories anymore just now. I'm getting the following error using this example command:

instagram-scraper -u USER -p PASSWORD -f C:\ig_users.txt -d C:\SavedStories -n -t story --latest --interactive --retry-forever 

Traceback (most recent call last):
  File "C:\Python361\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.32', 'console_scripts', 'instagram-scraper')()
  File "c:\python361\lib\site-packages\instagram_scraper\app.py", line 1133, in main
    scraper.login()
  File "c:\python361\lib\site-packages\instagram_scraper\app.py", line 213, in login
    self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "c:\python361\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "c:\python361\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by dmoreno1994** [comment]
Look the solution that I proposed in #231. The problem is login function.

**Comment by clublek** [comment]
@dmoreno1994: Your latest commit does not work with a userfile.txt. It only downloads the stories of the first user, but then hangs...
