### ISSUE TITLE
Error when executing simple scrape: KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by sergiers3** [rarcega/instagram-scraper#236]
Im getting this error while I try to execute a simple scrap:

`$ sudo instagram-scraper zuck -u username -p password`

Here the error:

`Traceback (most recent call last):
  File "/Users/user/PycharmProjects/virtENV/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.34', 'console_scripts', 'instagram-scraper')()
  File "/Users/user/PycharmProjects/virtENV/lib/python3.6/site-packages/instagram_scraper/app.py", line 1157, in main
    scraper.login()
  File "/Users/user/PycharmProjects/virtENV/lib/python3.6/site-packages/instagram_scraper/app.py", line 213, in login
    self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "/Users/user/PycharmProjects/virtENV/lib/python3.6/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Users/user/PycharmProjects/virtENV/lib/python3.6/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
(virtENV) 
`

**Comment by Emalton** [comment]
I can't reproduce with the newest build, I think this was fixed.

**Comment by Fireshadow3** [comment]
Same bug for me, I get:
`Traceback (most recent call last):
  File "/usr/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.35', 'console_scripts', 'instagram-scraper')()
  File "/usr/lib/python3.6/site-packages/instagram_scraper/app.py", line 1185, in main
    scraper.login()
  File "/usr/lib/python3.6/site-packages/instagram_scraper/app.py", line 214, in login
    self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "/usr/lib/python3.6/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3.6/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"`
When trying to download any instagram account.

**Comment by VasiliPupkin256** [comment]
This is supposed to be fixed in master branch but the new version is not released to pypi yet

**Comment by Fireshadow3** [comment]
With 1.5.36 the problem is fixed for me!

**Comment by sergiers3** [comment]
Works fine now, thanks!

**Comment by Felzow47** [comment]
> Hi. See also #233 #231 #235. You have to edit your app.py file and change these [3 lines](https://github.com/dmoreno1994/instagram-scraper/commit/8f125465ce76c0a6a057913b37153e6e6c3106d5). Don't mind the exact line numbers, they are different now. Then you can login and get the stories of that account or maybe more. I just get stories and no pictures or videos from the user page but it seems others have no problem. If you get it running, it would be nice, if you let us know if you get more than just the stories.

not working for me with the 1.10.3 update
