### ISSUE TITLE
IMPORTANT: Current problems in a nutshell

### ISSUE THREAD

**Issue by thewracl** [rarcega/instagram-scraper#238]
Clearly, this is now getting really weird. Every morning there is a new version of the scraper and it is still totally broken.

There must be some kind of total miscommunication here. So let me spell it out for you! @rarcega

First I upgrade instagram-scraper to the latest version:
`pip install instagram-scraper --upgrade`

After that, I do a very simple scrap:

```
user@instagramscrapertesthost ~ $ instagram-scraper zuck -u xxxxxxxx -p yyyyyyyy
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.35', 'console_scripts', 'instagram-scraper')()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 1185, in main
    scraper.login()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 214, in login
    self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

```
As you can see, the CSRFtoken is broken so I apply that changes to /usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py according to the CSRFtoken fix from @dmoreno1994: 

Line 211:
`self.session.headers.update({'Referer': BASE_URL})`
to
`self.session.headers.update({'Referer': BASE_URL, 'user-agent': STORIES_UA})`

and 

Line 214:
`self.session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})`
to
`self.session.headers.update({'X-CSRFToken': req.cookies.get_dict()['csrftoken']})`

After that I can use the scraper without the csrftoken warning:

```
user@instagramscrapertesthost ~ $ instagram-scraper zuck -u xxxxxxxx -p yyyyyyyy
Searching zuck for profile pic: 100% 1/1 [00:00<00:00, 258.00 images/s]
Searching zuck for stories: 0 media [00:00, ? media/s]
Searching zuck for posts: 127 media [00:06, 18.59 media/s]
Downloading: 100%|##########| 10/10 [00:00<00:00, 16.03it/s]
```

All seems fine, but I only get these from the account:

```
user@instagramscrapertesthost ~/zuck $ ls
13383998_580283535475923_1793402328_n.mp4
13408265_1308807495815230_1941796234_n.mp4
13739633_1648409658810275_999417478_a.jpg
13770715_900055343473157_1044264756_n.mp4
13827894_330573417274518_1957569032_n.mp4
17192719_235458343584819_3768123655167410176_n.mp4
18576318_627061647486278_6323406467873374208_n.mp4
18578230_298711620556980_29209239356440576_n.mp4
18785492_363552097376067_2540351062548676608_n.mp4
19646615_1888106204778757_4890449844277084160_n.mp4
user@instagramscrapertesthost ~/zuck $ 
```
The media files are recognized but not downloaded, only the stories (I guess). At least it is always the stories on other (private) accounts for me. Never a picture someone has posted.

I really hope, this is all more clear now and you fix the scraper soon. If you are unable to verify my findings then give me at least some clues how I can activate some more log files that shows what URL was tried to download and what the errorcode was.

**Comment by senorguapo** [comment]
In my case it's only downloading videos (no stories).

**Comment by thewracl** [comment]
Wow, this is just crazy. No wonder we get no fix for that when everyone else has different problems or none. Maybe it is IP-based because it can't be account-based. Created a bunch of different accounts on my VMs; all missed the pictures and videos (media)

**Comment by Gitiboy** [comment]
Same problem as @senorguapo.

Further in addition. It seems Instagram is unto me:

Code:
`instagram-scraper -u XXXXX -p XXXXX --location 220112037 --media-metadata --include-location --retry-forever`

Error:
`ERROR: Login failed for [XXXXX]
ERROR: Please verify your account at https://www.instagram.com/challenge/XXXXXXX/XXXXXXX/
Searching 220112037 for posts: 0 media [00:00, ? media/s]Traceback (most recent call last):
  File "C:\xxx\xxx\AppData\Local\Programs\Python\Python36\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.35', 'console_scripts', 'instagram-scraper')()
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 1190, in main
    scraper.scrape_location()
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 373, in scrape_location
    self.__scrape_query(self.query_location_gen)
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 401, in __scrape_query
    disable=self.quiet):
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\tqdm\_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 452, in __query_gen
    nodes, end_cursor = self.__query(url, variables, entity_name, query, end_cursor)
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 469, in __query
    self.update_ig_gis_header(params)
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 779, in update_ig_gis_header
    params
  File "c:\xxx\xxx\appdata\local\programs\python\python36\lib\site-packages\instagram_scraper\app.py", line 769, in get_ig_gis
    data = rhx_gis + ":" + params
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

When going to instagram it says "unusual login attempt detected".

**Comment by VasiliPupkin256** [comment]
```
Searching zuck for posts: 127 media [00:06, 18.59 media/s]
Downloading: 100%|##########| 10/10 [00:00<00:00, 16.03it/s]
```
This is weird. This shouldn't happen due to rate limiting errors or similar. Can you debug it further to see where the media urls were dropped? Don't you run it with `--letest` switch or similar?

**Comment by thewracl** [comment]
@VasiliPupkin256 
I did not use any special switches, just the command I copy and pasted. I would be happy to debug it further if you tell me how! Tried the `--verbose 1` switch but it showed me nothing. What do you get when you run that command `instagram-scraper zuck -u xxxxxxxx -p yyyyyyyy`?

**Comment by VasiliPupkin256** [comment]
@thewracl you can use debugger like PyCharm, ideally, but it can also be achieved using debug output through the calls to `self.logger`. The media is probably filtered in the function `get_media`in its main for loop. So you should check it. It should submit all the media urls to `executor.submit(self.worker_wrapper, self.download, item, dst)`, if the line is called fever than 127 times then it is a good point to start the debug and go up the stack, check `query_media_gen` etc. So at first either run it in debugger or add the line `self.logger.warning('found item')` before the call to `executor.submit(...)` (there is two such calls in the function `get_media`) and check the output in instagram-scraper.log

**Comment by thewracl** [comment]
@VasiliPupkin256
The instagram-scraper.log looks like this:
```
2018-05-25 18:17:35,306 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:41,270 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:41,271 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:41,272 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:41,273 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:45,500 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:45,501 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:45,502 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:47,329 - instagram_scraper.app - WARNING - found item
2018-05-25 18:17:47,330 - instagram_scraper.app - WARNING - found item
```
What to do next? Please only with logger messages because I really don't know how to debug.

As you have probably not seen it before because I edited the post:
What do you get when you run that command `instagram-scraper zuck -u xxxxxxxx -p yyyyyyyy`? Do you also have to patch the CSRFToken or does it work for you without doing anything (just plan simple 1.5.35)?

**Comment by VasiliPupkin256** [comment]
@thewracl I am getting all the 127 files + profile pic

```
Searching zuck for profile pic: 100% 1/1 [00:00<?, ? images/s]
Searching zuck for stories: 0 media [00:00, ? media/s]
Searching zuck for posts: 127 media [00:17,  7.21 media/s]
Downloading: 100%|###########################| 128/128 [01:01<00:00,  2.09it/s]
```

Ok, now you need to add different log messages in the code above. Try to add `self.logger.warning('log {0} {1}'.format(self.has_selected_media_types(item), self.is_new_media(item)) )` before the `if self.has_selected_media_types(item) and self.is_new_media(item):` statement

**Comment by thewracl** [comment]
@VasiliPupkin256
This is the log file:
```
2018-05-25 20:25:12,330 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,331 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,331 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,331 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,331 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,331 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,331 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,331 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,332 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,333 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,334 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,334 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,334 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,334 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,334 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:12,335 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,336 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,336 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,337 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,338 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,338 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,338 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,338 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:12,339 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,340 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,340 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,342 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,342 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,342 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:12,343 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:12,346 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,346 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,349 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:12,349 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,665 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,666 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,666 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,666 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,666 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,667 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,667 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,667 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,667 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,667 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:26,667 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,668 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,668 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,668 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,669 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,671 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,671 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,672 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,672 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,672 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,672 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,672 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,673 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,674 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,675 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,675 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,675 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,675 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:26,675 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:26,675 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,676 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,676 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,676 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,676 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,676 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:26,676 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,917 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,917 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,917 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,917 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,918 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,918 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,918 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,918 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,918 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,918 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,918 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,919 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,919 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,919 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,919 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,919 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:32,919 - instagram_scraper.app - WARNING - log True True
2018-05-25 20:25:32,919 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,920 - instagram_scraper.app - WARNING - log False True
2018-05-25 20:25:32,921 - instagram_scraper.app - WARNING - log False True
```
Interesting! Did you also change your login procedure with the CSRFTtoken patch?

**Comment by VasiliPupkin256** [comment]
@thewracl ouch, I didn't apply the csrftoken patch, I though that is was already merged and the poll request #234 is closed. With the patch it doesn't work. I figured out the bug and will make PR if it pass the batch test. Are you sure that it doesn't work without this 'user-agent': STORIES_UA? What is it telling you?

**Comment by VasiliPupkin256** [comment]
@thewracl please test the pull request

**Comment by thewracl** [comment]
@VasiliPupkin256
Looking good! I now got all 128 files. I'm going to test it now on a much larger batch of accounts. Will let you know what happens. This will take some time because of the 429 throttle
It sure does not work without the user agent. I don't remember exactly the error message but I think it was the the same as in the opening post. It just seems Instagram does not send me the Token without an user-agent

**Comment by thewracl** [comment]
@VasiliPupkin256
Well, I just finished my tests. Scraped about 300 accounts without problems and they look complete to me. Thanks for your work!

**Comment by sebnitzer** [comment]
Hi there, apologies to bother on this topic. For some reason the fixes above don't help in my case. I still got the error:

line 770, in get_ig_gis
    data = rhx_gis + ":" + params
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Many thanks in advance
