### ISSUE TITLE
Even when username and password are provided, the tool complains that they are not.

### ISSUE THREAD

**Issue by mtcjayne** [rarcega/instagram-scraper#241]
When using `--user-login user` and `--user-pass pass` on the command line I get the argument list, the filename format codes, and
`Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 1158, in main
    raise ValueError('Must provide username(s) OR a file containing a list of username(s)')
ValueError: Must provide username(s) OR a file containing a list of username(s)`
and when providing them in a file in the form of
`-u=user
-p=pass`
I get the argument list and
`instagram-scraper: error: argument --login-user/--login_user/-u is required`

**Comment by mtcjayne** [comment]
This occurred when I failed to include whitespace between the final argument and the username to be scraped. It's not an error with what I thought it was, but it might be good to see if there's a more helpful error message to include, such as "No username to scrape was included"
