### ISSUE TITLE
Solution for road blocked accounts

### ISSUE THREAD

**Issue by thewracl** [rarcega/instagram-scraper#259]
I had a road block on one of my accounts ("suspicious behavior"). Tried to -i so I can get the code but that didn't work. See also #247 

But I found the solution to that! All lies in the outdated user-agents in the constants.py. I will not give you just another string but I will tell you how you find an alternative user-agent just for you:

old one:
`CHROME_WIN_UA = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'`
change the 59.0.3071.115 to something newer. Use this for [reference](developers.whatsmybrowser.com/useragents/explore/software_name/chrome/)

Now to the more important:
`#STORIES_UA = 'Instagram 9.5.2 (iPhone7,2; iPhone OS 9_3_3; en_US; en-US; scale=2.00; 750x1334) AppleWebKit/420+'`
You have to change several things: 
**9.5.2** to a newer version, use [this](www.apkmirror.com/apk/instagram/instagram-instagram/) for reference. You only need to change the version.
Next to the simulated Iphone, take a newer Iphone's user string and change **iPhone7,2; iPhone OS 9_3_3;** and also **AppleWebKit/420+**
Use [this](developers.whatsmybrowser.com/useragents/explore/operating_platform/iphone/) again for reference

After changing the constants.py clear the road block normally in your browser and then start the scraper again. It worked for me and it should also work for you.

@rarcega @VasiliPupkin256 
I don't know if it is safe to just use another user agent for all the scrapers or if it is better to let the scraper choose from let's say 10 combinations ...

**Comment by VasiliPupkin256** [comment]
But what constants do you use? You can edit the file and make a pull request right from the browser here on github

**Comment by nicolomessina** [comment]
This doesn't work for me

**Comment by firstneithernorlast** [comment]
@thewracl 
I'm not able to open those reference links you posted. Could you post another reference please?

**Comment by thewracl** [comment]
@firstneithernorlast 
I updated the links in the opening post

@perturbator8 
Make sure your IP is not blocked! If you have a static IP wait for 24 hours to get cleared. Otherwise just get a new IP. Then change the user agent and retry. It worked for me a couple of times.

**Comment by perturbator8** [comment]
Thank you. Locally it works. My issue now is when I load it on Heroku. At each call IP changes and probably Instagram block my call asking me a challenge to confirm to be me. Similar to issue #131

**Comment by thewracl** [comment]
@perturbator8 Sorry, I can't help you there. I only use it locally on my machine(s) and don't use Heroku. It seems, the problem was there a long time before the road blocks that occurred since a few weeks ago.

**Comment by 4TJMn** [comment]
some kind of cookie storage would be nice so the script would not need to log in every time it runs. it might look suspicious if you download things from multiple profiles and log in/out often.

**Comment by pabloab** [comment]
Seems to work with _`--interactive`, `-i` Enable interactive login challenge solving_.

**Comment by vii33** [comment]
This is currently an issue, again. 

Tried several newer iOS Versions: No changes, same authentication problem.

Tried several API Versions: If the number differes from the original one (`123.0.0.21.114`) I get the following error:

```
Traceback (most recent call last):
  File "app.py", line 1630, in main
    scraper.authenticate_with_login()
  File "app.py", line 259, in authenticate_with_login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "...\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "...\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

Example: `Instagram 170.0.0.30.474 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X; en_US; en-US; scale=2.00; 750x1334) AppleWebKit/605.1.15'`

**Comment by TheMrRandomDude** [comment]
> This is currently an issue, again.
> 
> Tried several newer iOS Versions: No changes, same authentication problem.
> 
> Tried several API Versions: If the number differes from the original one (`123.0.0.21.114`) I get the following error:
> 
> ```
> Traceback (most recent call last):
>   File "app.py", line 1630, in main
>     scraper.authenticate_with_login()
>   File "app.py", line 259, in authenticate_with_login
>     self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
>   File "...\cookies.py", line 328, in __getitem__
>     return self._find_no_duplicates(name)
>   File "...\cookies.py", line 399, in _find_no_duplicates
>     raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> KeyError: "name='csrftoken', domain=None, path=None"
> ```
> 
> Example: `Instagram 170.0.0.30.474 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X; en_US; en-US; scale=2.00; 750x1334) AppleWebKit/605.1.15'`
> 
> Tried also using the `--cookiejar` option as stated in #598. Did not help, though.

Just to confirm, also having issue. One account got blocked.

Have you managed to find a solution or an alternative? @vii33

**Comment by savosta1** [comment]
tell me today this method will help unlock your instagram account?
