### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.instagram.com/

### ISSUE THREAD

**Issue by moodiest** [rarcega/instagram-scraper#273]
Whenever I run my script I always get the following error:
```Repeated error HTTPError(u'400 Client Error: Bad Request for url: https://www.instagram.com/',)
(A)bort, (I)gnore, (R)etry or retry (F)orever?a
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\instagram-scraper.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 1211, in main
    scraper.login()
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 224, in login
    self.rhx_gis = self.get_shared_data()['rhx_gis']
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 710, in get_shared_data
    resp = self.get_json(BASE_URL + username)
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 204, in get_json
    resp = self.safe_get(*args, **kwargs)
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 174, in safe_get
    response.raise_for_status()
  File "c:\python27\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.instagram.com/
```

The script I'm running is:
`C:\Python27\Scripts\instagram-scraper instagram @D:\story\Instagram\instagram-scraper\insta_args.txt --latest --media-metadata --template "{year}-{month}-{day} {h}.{m}.{s} - {urlname}"`

**Comment by luisalancruz** [comment]
mi cuenta no entra
