### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None" (1.5.38)

### ISSUE THREAD

**Issue by davewgsn** [rarcega/instagram-scraper#279]
Beginning the afternoon of August 16th I've been getting the same error described in #236 when I try to do any simple request, e.g. `instagram-scraper someuser -u xxxx -p xxxx -t image`. I do have the latest version from pip (1.5.38) which contains the fix, and it was working earlier in the day.

Is anyone else seeing this issue? I wonder if perhaps Instagram just pushed another change to their API.

```
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 1211, in main
    scraper.login()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 218, in login
    self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

**Comment by akhepcat** [comment]
Just ran into this as well, whilst trying to figure out how to deal with 2FA.  Sigh.

**Comment by bschollnick** [comment]
I am also seeing this issue as of 8/17/2018 @ 6:34am.

**Comment by pyfrog** [comment]
same issue

**Comment by pr1m3r** [comment]
Same here. It looks like it is running into status `400 `on `login()` when it requests the `LOGIN_URL = BASE_URL + 'accounts/login/ajax/'`

Searching for a way to fix it. I guess thats an issue with the user-agent again. Anybody got a chance to find out the latest user-agent of the iOS app or is able to tell me the exact version? It has to look like `58.0.x.x.x`

**Comment by 501st-alpha1** [comment]
I got this error earlier, and when I logged in manually immediately afterward, I was asked to add a phone number to verify my account.  I haven't gotten the error again since doing so.

**Comment by malagebidi** [comment]
same issue from yesterday morning.

**Comment by fightmaxime** [comment]
Same issue, since yesterday.

**Comment by pr1m3r** [comment]
Have you tried logging in manually with a web browser, preferably with the one that has exactly the user-agent specified in the `constants.py` like the default `CHROME_WIN_UA = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36'` and with the same ip address your script is running with? Is there some kind of challenge?

I faced this kind of issue and guess that the cause of the status `400` I have got on requesting `LOGIN_URL = BASE_URL + 'accounts/login/ajax/'`. The response-cookies, set to `login.cookies`, in fact contained no cookie named `'csrftoken'`.

**Comment by pr1m3r** [comment]
Yeah, I think so..

Fixed it for me, but it get a bit hacky again. You can check out [my latest branch](/pr1m3r/instagram-scraper/tree/patch-2) (https://github.com/pr1m3r/instagram-scraper/commit/90148d918f701c93254865ea165524b554f3af65). I refactored the `login_challenge()` a lot to get it working but I am going to build it back to the previous version with only slight difference. Also notice that there is a new constant `BASE_LOGIN_URL` in the `constants.py` file. 

Check it out and as always let me know if it suits you or you are facing another issue.

**Comment by 4TJMn** [comment]
works for me too with python 3.7 on linux.

**Comment by maersu** [comment]
@pr1m3r works for me! (OSX, py3.6)

**Comment by Florian-rbn** [comment]
I have the same issue tooday.
I run this type of commande line and after I think 5 tries, it show me the same error
instagram-scraper -d [Directorypath] -n user  --cookiejar [cookiespath]/cookies.txt --latest-stamps [StampPath]/Stamp.txt -u user -p pwd -t [type] -m 3 --media-metadata --include-location --profile-metadata --comments
