### ISSUE TITLE
issues with scraping 

### ISSUE THREAD

**Issue by hengrumay** [rarcega/instagram-scraper#28]
Traceback (most recent call last):
  File "/Users/hrm/anaconda3/envs/scraperenv/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==0.1', 'console_scripts', 'instagram-scraper')()
  File "/Users/hrm/anaconda3/envs/scraperenv/lib/python3.5/site-packages/instagram_scraper-0.1-py3.5.egg/instagram_scraper/app.py", line 291, in main
    scraper.scrape()
  File "/Users/hrm/anaconda3/envs/scraperenv/lib/python3.5/site-packages/instagram_scraper-0.1-py3.5.egg/instagram_scraper/app.py", line 106, in scrape
    if '11906329_960233084022564_1448528159' not in user['profile_pic_url_hd']:                    
KeyError: 'profile_pic_url_hd'

Not sure what is causing the KeyError. Would appreciate help! Thanks.

**Comment by rarcega** [comment]
Thanks for the feedback. Looks like the key containing the url to the profile picture doesn't exist in the user metadata object. Either instagram has changed something on their end or this is particular to the user. I'll take a look.

**Comment by hengrumay** [comment]
Thanks for writing back -- I think it might be some usernames. It worked 
for some other usernames. Thanks for sharing the scraper app!
