### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None"

### ISSUE THREAD

**Issue by FlexibleToast** [rarcega/instagram-scraper#281]
Error started to occur recently (past few days maybe), still persists after update.

Traceback (most recent call last):
    File "/usr/local/bin/instagram-scraper", line 11, in <module>                                  sys.exit(main())
    File "/usr/local/lib/python3.5/dist-packages/instagram_scraper/app.py", line 1211, in main     
scraper.login()
    File "/usr/local/lib/python3.5/dist-packages/instagram_scraper/app.py", line 218, in login     self.session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})                   File "/usr/local/lib/python3.5/dist-packages/requests/cookies.py", line 328, in __getitem__    return self._find_no_duplicates(name)
    File "/usr/local/lib/python3.5/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))                     KeyError: "name='csrftoken', domain=None, path=None"

**Comment by 501st-alpha1** [comment]
This is a duplicate of #279.  From [my comment in that issue](https://github.com/rarcega/instagram-scraper/issues/279#issuecomment-413993782):

> I got this error earlier, and when I logged in manually immediately afterward, I was asked to add a phone number to verify my account. I haven't gotten the error again since doing so.

Otherwise, there's a possible solution [here](https://github.com/rarcega/instagram-scraper/issues/279#issuecomment-414055699).

**Comment by FlexibleToast** [comment]
Thanks, it was asking for me to verify through my email. Normally it gives the url and for the challenge code. This error threw me off. Now it doesn't error, but it doesn't seem to be doing anything.

**Comment by 501st-alpha1** [comment]
For that one see #278, #277, and [this patch](https://github.com/rarcega/instagram-scraper/issues/278#issuecomment-413615983).

**Comment by 501st-alpha1** [comment]
Download the source from #277:

```
git clone git@github.com:pr1m3r/instagram-scraper.git --branch patch-1
```

Then apply [this patch](https://github.com/rarcega/instagram-scraper/files/2311622/session.txt) with:

```
git apply session.txt
```

And install your new version with e.g.:
```
sudo python3 setup.py install
```

**Comment by FlexibleToast** [comment]
The first command fails saying there isn't a repository. So I tried:
`git clone https://github.com/pr1m3r/instagram-scraper.git --branch patch-1`
It worked, but then the git apply doesn't work because it looks for instagram_scraper. So, I changed that and it still fails because there is no app.py in the instagram-scraper directory.

I feel like there is something easy that I'm just missing...

**Comment by 501st-alpha1** [comment]
Sorry, forgot to say: between `git clone` and `git apply`, `cd` into newly downloaded directory, e.g.:
```
cd instagram-scraper
```
Applying the original patch from there should work.

**Comment by FlexibleToast** [comment]
Thanks, I'm back in business. How do I keep this up to date? Do I do this same process, or will this be merged and I can use pip to install future updates?

**Comment by 501st-alpha1** [comment]
Yes, hopefully it will be merged in eventually.
