### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by Kaidanov** [rarcega/instagram-scraper#295]
How can I scrape ? What is the problem here?

(base) D:\>instagram-scraper <wantedtag> --tag -u  <myuser> -p <mypass>  --maximum 4
Exception ignored in: <bound method tqdm.__del__ of Searching bodytype for posts: 1 media [00:43, 39.05s/ media]>
Traceback (most recent call last):##########################################################################################| 4/4 [00:04<00:00,  1.03s/it]
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tqdm\_tqdm.py", line 889, in __del__
    self.close()
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tqdm\_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tqdm\_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\site-packages\tqdm\_monitor.py", line 52, in exit
    self.join()
  File "c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by hernandcb** [comment]
It seems to be due to a [bug in tqdm](https://github.com/tqdm/tqdm/issues/613) that is closed now.
I updated it to the version 4.30 and now I can use the -m argument without problems.
