### ISSUE TITLE
KeyError on fetching profilepage

### ISSUE THREAD

**Issue by juliandortmund** [rarcega/instagram-scraper#31]
When I fetch a private profile, the following error pops up:
```shell
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 9, in <module>
    load_entry_point('instagram-scraper==0.1', 'console_scripts', 'instagram-scraper')()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-0.1-py2.7.egg/instagram_scraper/app.py", line 291, in main
    scraper.scrape()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-0.1-py2.7.egg/instagram_scraper/app.py", line 102, in scrape
    user = self.fetch_user(username)
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-0.1-py2.7.egg/instagram_scraper/app.py", line 144, in fetch_user
    return json.loads(shared_data)['entry_data']['ProfilePage'][0]['user']
KeyError: 'ProfilePage'
```
Seems that it is not guaranteed that `ProfilePage` is send back from instagram.

**Comment by rarcega** [comment]
The profile is fetched in order to get the profile picture and any stories posted by the user. It was assumed it should exist for every user but it may not. Does it work for certain user ids and not others when fetching private accounts? Would you be able to provide the user id so I can replicate?
