### ISSUE TITLE
Failed to establish a new connection: [WinError 10060]

### ISSUE THREAD

**Issue by yatoome** [rarcega/instagram-scraper#314]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mango\appdata\local\programs\python\python37\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.5.40', 'console_scripts', 'instagram-scraper')()
  File "c:\users\mango\appdata\local\programs\python\python37\lib\site-packages\instagram_scraper\app.py", line 1216, in main
    scraper.login()
  File "c:\users\mango\appdata\local\programs\python\python37\lib\site-packages\instagram_scraper\app.py", line 212, in login
    req = self.session.get(BASE_URL)
  File "c:\users\mango\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\mango\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\mango\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\mango\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F4A6011B70>: Failed to establish a new connection: [WinError 10060] 

please help

**Comment by dashrath1526** [comment]
I am also having the same issue.
