### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by moodiest** [rarcega/instagram-scraper#345]
When running my script to scrape posts from a list of accounts, I am getting a JSON decode error.

```
$ C:\Python27\Scripts\instagram-scraper -f usernames.txt @D:\story\Instagram\instagram-scraper\insta_args.txt --latest --media-metadata --template "{year}-{month}-{day} {h}.{m}.{s} - {urlname}"
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code exec code in run_globals
  File "C:\Python27\Scripts\instagram-scraper.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 1227, in main scraper.login()
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 224, in login login_text = json.loads(login.text)
  File "c:\python27\lib\json\__init__.py", line 339, in loads return _default_decoder.decode(s)
  File "c:\python27\lib\json\decoder.py", line 364, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python27\lib\json\decoder.py", line 382, in raw_decode raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded```

**Comment by nnoniash** [comment]
I am also getting the same error, please help

**Comment by samelsn2** [comment]
same, error 500

**Comment by VasiliPupkin256** [comment]
Instagram is barely working today. See reports on https://downdetector.com/status/instagram

**Comment by samelsn2** [comment]
> Instagram is barely working today. See reports on https://downdetector.com/status/instagram

oh whoops, thanks for the update.

**Comment by moodiest** [comment]
> Instagram is barely working today. See reports on https://downdetector.com/status/instagram

Ah, alright, makes sense. Not encountering this issue anymore now.
