### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by moodiest** [rarcega/instagram-scraper#346]
So I'm getting an indexerror when scanning and downloading an account.
```
Searching jakewarden for profile pic: 100% 1/1 [00:00<?, ? images/s]
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\instagram-scraper.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 1236, in main
    scraper.scrape()
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 578, in scrape
    self.get_stories(dst, executor, future_to_item, user, username)
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 651, in get_stories
    stories = self.fetch_stories(user['id'])
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 732, in fetch_stories
    return [self.set_story_url(item) for item in retval['data']['reels_media'][0]['items']]
  File "c:\python27\lib\site-packages\instagram_scraper\app.py", line 847, in set_story_url
    urls.append(item['video_resources'][-1]['src'])
IndexError: list index out of range```

**Comment by clublek** [comment]
Got the same issue for several profiles. Maybe it has to do something with the outage of Instagram yesterday??

**Comment by moodiest** [comment]
> Got the same issue for several profiles. Maybe it has to do something with the outage of Instagram yesterday??

It kept happening on the same profile for me, tried running it multiple times as well but it persisted. Just tried running it again this evening and it's still happening.
Other accounts were working fine apart from this one so I'm not sure it's related to the outage.

**Comment by ano0** [comment]
it probably is because its happening on multiple profiles. maybe its some url changes again..
