### ISSUE TITLE
Object does not support indexing

### ISSUE THREAD

**Issue by necrogami** [rarcega/instagram-scraper#359]
```
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/instagram_scraper/app.py", line 1384, in main
    scraper.scrape()
  File "/usr/local/lib/python3.6/dist-packages/instagram_scraper/app.py", line 666, in scrape
    self.merge_json({ 'GraphImages': self.posts }, '{0}/{1}.json'.format(dst, username))
  File "/usr/local/lib/python3.6/dist-packages/instagram_scraper/app.py", line 1155, in merge_json
    key = merged.keys()[0]
TypeError: 'dict_keys' object does not support indexing
```

This happens when running new with `--media-metadata`
Latest version 1.6 update.

**Comment by reliefs** [comment]
same issue,  https://github.com/instagrambot/Instagram-scraper-with-autopost/issues/4
