### ISSUE TITLE
Videos not found, causes crash

### ISSUE THREAD

**Issue by bschollnick** [rarcega/instagram-scraper#38]
Searching brielarson for posts: 0 media [00:00, ? media/s]Traceback (most recent call last):
  File "/Users/Benjamin/library/Python/2.7/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 315, in main
    scraper.scrape()
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 134, in scrape
    unit=' media', disable=self.quiet):
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 180, in media_gen
    media = self.fetch_media_json(username, max_id=None)
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 208, in fetch_media_json
    media['items'] = [self.set_media_url(item) for item in media['items']]
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 215, in set_media_url
    item['url'] = item[item['type'] + 's']['standard_resolution']['url'].split('?')[0]
KeyError: u'videos'

It appears that some accounts may not have videos?  

This wasn't happening earlier, so it appears the videos folder has been removed from the user?  And instagram-scraper is working fine on some other accounts.

**Comment by CNG** [comment]
I'm having the same issue.

**Comment by rarcega** [comment]
@CNG Sure, if you can provide me with an example that would be helpful in diagnosing the problem.

**Comment by CNG** [comment]
@rarcega Emailed to your website contact address.

**Comment by CNG** [comment]
Per @rarcega‘s report the users in my list did not cause errors for him, I retried and this time got no errors, without updating anything. I wish I looked into it more at the time… perhaps it was something on Instagram‘s end. Are you still having the issue, @bschollnick ?

**Comment by bschollnick** [comment]
Sorry, I wasn't notified about the reply?

I haven't seen this issue in a while.  So it may have been a transient instagram issue?
