### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes' when using --media-metadata

### ISSUE THREAD

**Issue by Svekla** [rarcega/instagram-scraper#382]
`instagram-scraper -f list.txt -t image video story --login-user x --login-pass x --cookiejar cookies.txt --latest --media-metadata --template "{mediatype}_{date}-{h}{m}_{shortcode}"`

```
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.6.1', 'console_scripts', 'instagram-scraper')()
  File "/usr/local/lib/python3.4/dist-packages/instagram_scraper/app.py", line 1391, in main
    scraper.scrape()
  File "/usr/local/lib/python3.4/dist-packages/instagram_scraper/app.py", line 668, in scrape
    self.merge_json({ 'GraphImages': self.posts }, '{0}/{1}.json'.format(dst, username))
  File "/usr/local/lib/python3.4/dist-packages/instagram_scraper/app.py", line 1164, in merge_json
    self.save_json(merged, dst)
  File "/usr/local/lib/python3.4/dist-packages/instagram_scraper/app.py", line 1176, in save_json
    output_list.update(json.load(f))
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by VasiliPupkin256** [comment]
You are using python older than 3.6 https://github.com/rarcega/instagram-scraper/pull/364#issuecomment-489443195
