### ISSUE TITLE
Unsupported pickle protocol?

### ISSUE THREAD

**Issue by samsepiol59** [rarcega/instagram-scraper#423]
```Traceback (most recent call last):
  File "/home/samsepiol/.local/bin/instagram-scraper", line 10, in <module>
    sys.exit(main())
  File "/home/samsepiol/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 1366, in main
    scraper = InstagramScraper(**vars(args))
  File "/home/samsepiol/.local/lib/python2.7/site-packages/instagram_scraper/app.py", line 137, in __init__
    self.session.cookies.update(pickle.load(f))
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3```

This is the error I'm getting - I think it might be because the app requires python while my server automatically uses python3?! I have both installed though, so if there's a solution..! Thank you!

**Comment by aslmx** [comment]
I had the same today after updating IS.

If you follow back the call-tracer in your error message, there is a very slight hint that it occurs during loading the cookies.

I had not known what "pickle" does, but I now assume it is some object storage library ;)

**IS worked again after i renamed (or removed) the cookies that i used in the commandline.**

My assumption is, that the way cookies are stored is changed from one version to the next. If you continue to use the same cookies, IS will try to load them but fail as the format has changed (=> no backwards compatibility?).

It's a bit late for OP, but maybe next person can save some time debugging this ;)
