### ISSUE TITLE
KeyError: u'carousels'  starting today

### ISSUE THREAD

**Issue by akhepcat** [rarcega/instagram-scraper#43]
Today i started receiving this traceback error:

    Searching ACCOUNT for profile pic: 100% 1/1 [00:00<00:00, 2392.64 images/s]
    Searching ACCOUNT for stories: 0 media [00:00, ? media/s]
    Searching ACCOUNT for posts: 0 media [00:00, ? media/s]
    Traceback (most recent call last):
      File "/usr/local/bin/instagram-scraper", line 11, in <module>
        load_entry_point('instagram-scraper==1.0.0', 'console_scripts', 'instagram-scraper')()
      File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-1.0.0-py2.7.egg/instagram_scraper/app.py", line 304, in main
        scraper.scrape()
      File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-1.0.0-py2.7.egg/instagram_scraper/app.py", line 130, in scrape
        unit=' media', disable=self.quiet):
      File "build/bdist.linux-x86_64/egg/tqdm/_tqdm.py", line 787, in __iter__
      File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-1.0.0-py2.7.egg/instagram_scraper/app.py", line 180, in media_gen
        media = self.fetch_media_json(username, max_id)
      File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-1.0.0-py2.7.egg/instagram_scraper/app.py", line 201, in fetch_media_json
        media['items'] = [self.set_media_url(item) for item in media['items']]
      File "/usr/local/lib/python2.7/dist-packages/instagram_scraper-1.0.0-py2.7.egg/instagram_scraper/app.py", line 208, in set_media_url
        item['url'] = item[item['type'] + 's']['standard_resolution']['url'].split('?')[0]
    KeyError: u'carousels'

API change over at IG?

**Comment by rarcega** [comment]
This is fixed in the latest release 1.1.1. I have added support for scraping [carousel media](https://www.facebook.com/help/instagram/269314186824048?helpref=uf_permalink)

**Comment by akhepcat** [comment]
great quick fix.  Thanks!
