### ISSUE TITLE
$ instagram-scraper <username> -u <your username> -p <your password>

### ISSUE THREAD

**Issue by adefajar2018** [rarcega/instagram-scraper#444]
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/instagram_scraper-1.5.3-py2.7.egg/instagram_scraper/app.py", line 431, in media_gen
    media = self.fetch_media_json(username, max_id=None)
  File "/anaconda2/lib/python2.7/site-packages/instagram_scraper-1.5.3-py2.7.egg/instagram_scraper/app.py", line 464, in fetch_media_json
    raise ValueError('User {0} does not exist'.format(username))
ValueError: User lynaritaa does not exist

**Comment by VuBrian22** [comment]
1- Did you type in the username correctly?
2- Update Python to 7.3.4
3- Do not run it in the Anaconda IDE, only in the Bash (which you might already have done, this is just a reminder)
