### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by bschollnick** [rarcega/instagram-scraper#45]
This is just an FYI.

Executive summary, updating requests might of solved this issue?

Details:

When scrapping an instagram user, I received an unicode decoding error.

Traceback (most recent call last):
  File "/Users/Benjamin/library/Python/2.7/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 390, in main
    scraper.scrape()
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 126, in scrape
    self.get_media(dst, executor, future_to_item, username)
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 164, in get_media
    unit=' media', disable=self.quiet):
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 742, in __init__
    self.postfix))
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 199, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 192, in fp_write
    fp.write(_unicode(s))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 20: ordinal not in range(128)

I can't duplicate this again, but I noticed that the requests library was updated, when I went to try to duplicate this.

Requirement already up-to-date: instagram-scraper in /Users/Benjamin/Library/Python/2.7/lib/python/site-packages
Requirement already up-to-date: nose in /Users/Benjamin/Library/Python/2.7/lib/python/site-packages (from instagram-scraper)
Requirement already up-to-date: requests-mock in /Users/Benjamin/Library/Python/2.7/lib/python/site-packages (from instagram-scraper)
Requirement already up-to-date: tqdm>=3.8.0 in /Users/Benjamin/Library/Python/2.7/lib/python/site-packages (from instagram-scraper)
Collecting requests>=1.0.4 (from instagram-scraper)
  Using cached requests-2.13.0-py2.py3-none-any.whl

So it's possible this was a bug in requests?  I don't see anything obvious in requests that would solve this... But maybe?

2.12.5 (2017-01-18)
Bugfixes
Fixed an issue with JSON encoding detection, specifically detecting big-endian UTF-32 with BOM.

I'd swear that I was running a more current version of requests....

**Comment by bschollnick** [comment]
Okay, I can now reproduce it.  

It was the next account below the last entry it had outputted to the console.

I can reproduce it by asking instagram-scraper to scrape this account: https://www.instagram.com/kellyeden/

**Comment by rarcega** [comment]
I was unable to reproduce this error and was able to scrape that user's account without any issues. Can you please try again?

**Comment by bschollnick** [comment]
Nope...  Still dying...

Traceback (most recent call last):
  File "/Users/Benjamin/library/Python/2.7/bin/instagram-scraper", line 11, in <module>
    sys.exit(main())
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 520, in main
    scraper.scrape()
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 238, in scrape
    self.get_media(dst, executor, future_to_item, username)
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/instagram_scraper/app.py", line 288, in get_media
    unit=' media', disable=self.quiet):
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 742, in __init__
    self.postfix))
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 199, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/Users/Benjamin/Library/Python/2.7/lib/python/site-packages/tqdm/_tqdm.py", line 192, in fp_write
    fp.write(_unicode(s))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 20: ordinal not in range(128)

I'm using the following command line:

nerv:shellscripts Benjamin$ cat update_insta2.sh 
#
# Update Cfakes
shellscripts="/Users/Benjamin/dropbox/shellscripts"
storage="/Volumes/3TB_Drive/gallery/albums"

pip install --user --upgrade instagram-scraper
cd "$storage/instagram"
instagram-scraper -f "/Users/Benjamin/dropbox/shellscripts/instagram_accounts.txt"

**Comment by gvkalra** [comment]
Although the use case is different, the error seems to the same while scrapping non-english tags.

e.g : [투썸](https://www.instagram.com/explore/tags/%ED%88%AC%EC%8D%B8/)
```
$ instagram-scraper 투썸 --tag --media_metadata

Traceback (most recent call last):
  File "/home/gvkalra/Downloads/instagram-scraper/venv/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper', 'console_scripts', 'instagram-scraper')()
  File "/home/gvkalra/Downloads/instagram-scraper/instagram_scraper/app.py", line 620, in main
    scraper.scrape_hashtag()
  File "/home/gvkalra/Downloads/instagram-scraper/instagram_scraper/app.py", line 215, in scrape_hashtag
    disable=self.quiet):
  File "/home/gvkalra/Downloads/instagram-scraper/venv/local/lib/python2.7/site-packages/tqdm-4.11.2-py2.7.egg/tqdm/_tqdm.py", line 742, in __init__
    self.postfix))
  File "/home/gvkalra/Downloads/instagram-scraper/venv/local/lib/python2.7/site-packages/tqdm-4.11.2-py2.7.egg/tqdm/_tqdm.py", line 199, in print_status
    fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
  File "/home/gvkalra/Downloads/instagram-scraper/venv/local/lib/python2.7/site-packages/tqdm-4.11.2-py2.7.egg/tqdm/_tqdm.py", line 192, in fp_write
    fp.write(_unicode(s))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)

```
