### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by james3126** [rarcega/instagram-scraper#496]
Install appears to work fine. Once attempting to run instagram-scraper, I always get the following error:

`PS C:\Users\james\My Stuff> instagram-scraper demo_ig_scraper
Traceback (most recent call last):
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\Scripts\instagram-scraper-script.py", line 11, in <module>
    load_entry_point('instagram-scraper==1.8.0', 'console_scripts', 'instagram-scraper')()
  File "C:\Users\james\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instagram_scraper-1.8.0-py3.8.egg\instagram_scraper\app.py", line 1399, in main
    args.filter_locations = InstagramScraper.parse_delimited_str(','.join(args.filter_location))
TypeError: can only join an iterable`

**Comment by AlexNik** [comment]
@james3126 it was fixed here https://github.com/rarcega/instagram-scraper/pull/489
You should use previous release until it would be merged.
