### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ProudPenguin** [rarcega/instagram-scraper#507]
Passed options:
```bash
instagram-scraper \
    --login-user "username" \
    --login-pass "password" \
    --followings-input \
    --followings-output "output.txt" \
    --media-types "image,video" \
    --latest-stamps "timestamps.txt" \
    --media-metadata \
    --interactive
```

Result:
```
Traceback (most recent call last):
  File "/usr/local/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper==1.8.1', 'console_scripts', 'instagram-scraper')()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 1431, in main
    scraper.authenticate_with_login()
  File "/usr/local/lib/python2.7/dist-packages/instagram_scraper/app.py", line 253, in authenticate_with_login
    login_text = json.loads(login.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by VasiliPupkin256** [comment]
I had the same problem yesterday, but today it seems to settle down by itself
