### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by gvkalra** [rarcega/instagram-scraper#54]
While scraping the tag [투썸플레이스](https://www.instagram.com/explore/tags/%ED%88%AC%EC%8D%B8%ED%94%8C%EB%A0%88%EC%9D%B4%EC%8A%A4/), instagram-scraper dies after 12,030 media items, although there are 349,509 posts (as reported on the webpage of Instagram).

```
$ instagram-scraper 투썸플레이스 --media_metadata --tag 
Searching #투썸플레이스 for posts: 12030 media [06:15, 39.75 media/s]Traceback (most recent call last):
  File "/home/gvkalra/Downloads/instagram-scraper/venv/bin/instagram-scraper", line 11, in <module>
    load_entry_point('instagram-scraper', 'console_scripts', 'instagram-scraper')()
  File "/home/gvkalra/Downloads/instagram-scraper/instagram_scraper/app.py", line 627, in main
    scraper.scrape_hashtag()
  File "/home/gvkalra/Downloads/instagram-scraper/instagram_scraper/app.py", line 222, in scrape_hashtag
    disable=self.quiet):
  File "/home/gvkalra/Downloads/instagram-scraper/venv/local/lib/python2.7/site-packages/tqdm-4.11.2-py2.7.egg/tqdm/_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "/home/gvkalra/Downloads/instagram-scraper/instagram_scraper/app.py", line 267, in hashtag_media_gen
    media, end_cursor = self.query_hashtag(hashtag, end_cursor, csrftoken)
TypeError: 'NoneType' object is not iterable
Searching #투썸플레이스 for posts: 12030 media [06:30, 30.82 media/s]
```

I am investigating it more.

**Comment by SophMC** [comment]
I'm having trouble with this too - have you got anywhere with your investigations?

**Comment by ashgreat** [comment]
I am facing the same problem with both tag and location

**Comment by gvkalra** [comment]
@SophMC @ashgreat nope..

**Comment by Sieboldianus** [comment]
Try to replace Line 277 in app.py with the following:
`                try:
                    if self.include_location:
                        node['location'] = details.get('location')
                except AttributeError:
                    print("AttributeError detected (NoneType), skipping after 5 seconds..")
                    time.sleep(5)
                finally:    
                    self.extract_tags(node)`
