### ISSUE TITLE
Problem with Hangul (Korean) characters

### ISSUE THREAD

**Issue by mattstiles** [rarcega/instagram-scraper#83]
I get this error when running: 

`$ instagram-scraper 인형뽑기 --tag --maximum 10`

> Traceback (most recent call last):
>   File "/usr/local/bin/instagram-scraper", line 9, in <module>
>     load_entry_point('instagram-scraper==1.3.1', 'console_scripts', 'instagram-scraper')()
>   File "/Library/Python/2.7/site-packages/instagram_scraper/app.py", line 518, in main
>     scraper.scrape_hashtag()
>   File "/Library/Python/2.7/site-packages/instagram_scraper/app.py", line 130, in scrape_hashtag
>     disable=self.quiet):
>   File "/Library/Python/2.7/site-packages/tqdm/_tqdm.py", line 742, in __init__
>     self.postfix))
>   File "/Library/Python/2.7/site-packages/tqdm/_tqdm.py", line 199, in print_status
>     fp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))
>   File "/Library/Python/2.7/site-packages/tqdm/_tqdm.py", line 192, in fp_write
>     fp.write(_unicode(s))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 12: ordinal not in range(128)

I thought maybe it had been addressed in #45 but perhaps not? 

Here's the query on desktop: `https://www.instagram.com/explore/tags/%EC%9D%B8%ED%98%95%EB%BD%91%EA%B8%B0/`

Or: 

http://imgur.com/USfz7GB

**Comment by ansarirayyan** [comment]
I'm getting a similar issue when using Turkish characters
