### ISSUE TITLE
requests 2.18.4 with proxies throw SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

### ISSUE THREAD

**Issue by iacky** [rarcega/instagram-scraper#91]
Hi,
When I use requests 2.18.4 with proxies, it throw SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

MacOS Sierra
Python 3.6.2
OpenSSL 1.0.2l

pip3 list:

asn1crypto (0.22.0)
certifi (2017.7.27.1)
cffi (1.10.0)
chardet (3.0.4)
cryptography (2.0.3)
idna (2.6)
pycparser (2.18)
pyOpenSSL (17.2.0)
PySocks (1.6.7)
requests (2.18.4)
setuptools (28.8.0)
six (1.10.0)
tqdm (4.15.0)
urllib3 (1.22)

My code:

    import requests
    proxies={'http':'socks5://127.0.0.1:1080', 'https': 'socks5://127.0.0.1:1080'}
    r=requests.get('https://www.instagram.com/',proxies=proxies)
Error message:

        Traceback (most recent call last):
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
            cnx.do_handshake()
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1716, in do_handshake
            self._raise_ssl_error(self._ssl, result)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1449, in _raise_ssl_error
            raise SysCallError(-1, "Unexpected EOF")
        OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py", line 601, in urlopen
            chunked=chunked)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py", line 346, in _make_request
            self._validate_conn(conn)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py", line 850, in _validate_conn
            conn.connect()
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connection.py", line 326, in connect
            ssl_context=context)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
            return context.wrap_socket(sock, server_hostname=server_hostname)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
            raise ssl.SSLError('bad handshake: %r' % e)
        ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/adapters.py", line 440, in send
            timeout=timeout
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/connectionpool.py", line 639, in urlopen
            _stacktrace=sys.exc_info()[2])
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg/urllib3/util/retry.py", line 388, in increment
            raise MaxRetryError(_pool, url, error or ResponseError(cause))
        urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/Library/Frameworks/Python.framework/Versions/3.6/bin/instagram-scraper", line 11, in <module>
            load_entry_point('instagram-scraper', 'console_scripts', 'instagram-scraper')()
          File "/Users/wangwei/xingxing/scrape_instagram/instagram-scraper/instagram_scraper/app.py", line 763, in main
            scraper.scrape()
          File "/Users/wangwei/xingxing/scrape_instagram/instagram-scraper/instagram_scraper/app.py", line 346, in scrape
            self.login()
          File "/Users/wangwei/xingxing/scrape_instagram/instagram-scraper/instagram_scraper/app.py", line 97, in login
            req = self.session.get('https://www.instagram.com/',proxies =proxies)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 521, in get
            return self.request('GET', url, **kwargs)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 508, in request
            resp = self.send(prep, **send_kwargs)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 618, in send
            r = adapter.send(request, **kwargs)
          File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/adapters.py", line 506, in send
            raise SSLError(e, request=request)
        requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
        
 I want to know what the reason is, help me~~ thanks

**Comment by dansthemanwhosakid** [comment]
Also curious, bump
